apiVersion: v1
kind: Service
metadata:
  name: ai-plat-docs
  namespace: ai-plat
  labels:
    app.kubernetes.io/name: ai-plat-docs
spec:
  selector:
    app.kubernetes.io/name: ai-plat-docs
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
